server:
  port: 8080

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/(?<segment>.*), /${segment}

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/(?<segment>.*), /${segment}

        - id: ticket-service
          uri: lb://TICKET-SERVICE
          predicates:
            - Path=/api/tickets/**
          filters:
            - RewritePath=/api/(?<segment>.*), /${segment}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: your-very-long-secret-key-here
  expiration: 86400000
